### PR TITLE
feat: first implementation

### PR DESCRIPTION
**Pull request by atian25**
##### Checklist

- [x] `npm test` passes
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change

https://github.com/eggjs/egg/issues/1092

### CODE REVIEW

**Comment by atian25** [comment]
ping @OnedayLiu ~

**Comment by OnedayLiu** [comment]
我尽快弄弄~

**Comment by atian25** [comment]
可以 Review 了么?

**Comment by OnedayLiu** [comment]
可以 Review 了~

**Comment by atian25** [comment]
1.2.0

**Pull request merged**
